### ISSUE TITLE
Deadlock can happen when calling nvim api during handling notifications 

### ISSUE THREAD

**Issue by dzhou121** [neovim/go-client#18]
Deadlock happens when it stuck at

https://github.com/neovim/go-client/blob/master/msgpack/rpc/endpoint.go#L403
https://github.com/neovim/go-client/blob/master/msgpack/rpc/endpoint.go#L627
https://github.com/neovim/go-client/blob/master/msgpack/rpc/endpoint.go#L633
https://github.com/neovim/go-client/blob/master/msgpack/rpc/endpoint.go#L241

So it tries to ```e.handleNotification(messageLen)``` and put a notification into channel ```e.notifications```, it stuck because ```func (e *Endpoint) runNotifications()``` is stuck by a nvim api call ```c := <-e.Go(method, make(chan *Call, 1), reply, args...).Done``` inside the notification, because it needs ```e.handleReply(messageLen)``` which can't be executed because it's stuck at  ```e.handleNotification(messageLen)``` at the first place.

**Comment by garyburd** [comment]
See https://github.com/neovim/go-client/commit/2ba67b35ea08f186e4dc08c1fa298a69ced5a559.  

Reverting the change is not an option because this will prevent applications from handling "redraw" correctly.

One possible fix is to recognize when a blocking call is made from the [`runNotifications`](https://github.com/neovim/go-client/blob/c537b25422b5092f1224d70fd2844e937d7c696f/msgpack/rpc/endpoint.go#L633) goroutine and start a new goroutine to process the `notifications` channel.  This fix requires the addition of a context argument to handlers and all APIs.  

I think the best fix is to document that notifications are handled in a single goroutine and make it the responsibility of the application to start goroutines as needed.  To help applications debug deadloocks, the code that [sends notifications to the channel](https://github.com/neovim/go-client/blob/c537b25422b5092f1224d70fd2844e937d7c696f/msgpack/rpc/endpoint.go#L633) should log a message the first time the channel reaches full capacity.

**Comment by dzhou121** [comment]
What if the client really needs to retrieve some data from nvim inside the execution of a notification? 

Would it make sense to use mutex and start a new goroutine for ```handleNotification```, so that we don't block processing the msgpack messages, while mutex can preserve the executing order of notifications?

**Comment by garyburd** [comment]
Describe in more detail how you propose to preserve order.

**Comment by dzhou121** [comment]
Actually it won't work well, because the client could register to different methods, "redraw", "gui", etc. I'll just start goroutine accordingly in the application side. So this can be closed now.

Thank you for your help.

**Comment by garyburd** [comment]
The capacity of the `notifications` channel is 64.  Do you have any insight on why the channel filled to capacity?  Is nvim sending notifications faster than the application can process the notifications or is it possible that the call to nvim from the notification handler causes nvim to send more notifications?

If the channel filled to capacity because nvim is sent a burst of notifications faster than the application can process the notifications, then a fix is to remove the fixed capacity on the queue between the reader and `runNotifications`.  This implementation will use sync.Cond instead of channels.

**Comment by dzhou121** [comment]
This issues happened when I do ```:PlugUpdate```, and yes nvim sent notifications faster than my application can handle in this case.

**Comment by garyburd** [comment]
Removing the fixed capacity will fix :PlugUpdate. I'll make the change.
