### ISSUE TITLE
About HandleFunction

### ISSUE THREAD

**Issue by glepnir** [neovim/go-client#75]
I found `HandleFunciton` needs two args `options` and `fn interface{}`, the sceond arg is a interface type. so i define a function return a string send functionname as arg to it.got error.
but change the return value to (string,error) then it works...
```go
error:
func repoName() string {
	return repo.GetWorkPath()
}
right:
func repoName() (string,error) {
	return repo.GetWorkPath(),nil
}
p.HandleFunction(&plugin.FunctionOptions{Name: "GetRepoName"}, repoName)
```

**Comment by WhoIsSethDaniel** [comment]
Hello @zchee and @glepnir . I have created a repo https://github.com/WhoIsSethDaniel/nvim-go-client-examples that attempts to have many examples of how to use the Neovim go-client, along with documentation. I anticipate updating it more over time as I become more familiar with the client. 
For anyone involved with the neovim go-client feel free to link to this repo, if you want to.
Thank you.

**Comment by zchee** [comment]
@WhoIsSethDaniel thanks for share! also, your repository very helpful.
We would be better to your repository link to neovim/go-client README :)

And yeah, go-client has lot of API, also usage is tricky a bit.
e.g., Subscribe and Unsubscribe own event. I know this usage so can write code(actually, I wrote some code with that APIs) but still don't understand all.
contributing go-client example to your repository separately is make sense. because Go's `ExampleXXX` document has limited.

Anyway, thanks for write some examples!

**Comment by glepnir** [comment]
To be honest, I recently used lua to write neovim things, and participated in maintaining neovim's built-in lsp, it is very simple and powerful. I will read your example carefully when I have time, because I am a gopher and neovim also lacks some plugins written in go. Thanks for your work. 😄
